version: '3.7'
services:
  v2ray:
    build:
      context: ./proxy
    ports:
      - "51999:51999"
      - "51998:51998"
    restart: always
    volumes:
      - type: bind
        source: ./proxy/v2ray_config.json
        target: /v2ray/config.json
  frps:
    build:
      context: ./frps
    ports:
            #- "55000-60000:55000-60000"
      - "5000:5000"
      - "50000:51000"
    restart: always
    volumes:
      - type: bind
        source: ./frps/frps.ini
        target: /conf/frps.ini
